# Generated by Django 5.1.5 on 2025-01-22 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_is_premium'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='is_premium',
        ),
    ]
