# Generated by Django 5.1.5 on 2025-01-23 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='jee_chemistry_rank',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='jee_percentile',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='qualifications',
            field=models.TextField(blank=True, help_text='List your academic qualifications', null=True),
        ),
        migrations.AddField(
            model_name='mentor',
            name='teaching_style',
            field=models.TextField(blank=True, help_text='Describe your teaching approach', null=True),
        ),
    ]
