# Generated by Django 5.1.5 on 2025-01-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0002_mentor_jee_chemistry_rank_mentor_jee_percentile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='teaching_style',
        ),
        migrations.AlterField(
            model_name='mentor',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='qualifications',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='specialization',
            field=models.CharField(default='General Chemistry', max_length=100),
        ),
    ]
