# Generated by Django 5.1.5 on 2025-01-23 09:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0003_remove_mentor_teaching_style_alter_mentor_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorrequest',
            name='mentor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='mentors.mentor'),
        ),
        migrations.AlterField(
            model_name='mentorrequest',
            name='message',
            field=models.TextField(blank=True),
        ),
    ]
