# Generated by Django 5.1.5 on 2025-01-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0004_alter_mentorrequest_mentor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='mentor',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='bio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='jee_percentile',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='specialization',
            field=models.CharField(max_length=100),
        ),
    ]
