# Generated by Django 5.1.5 on 2025-01-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mentors', '0005_alter_mentor_options_mentor_name_alter_mentor_bio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mentor',
            name='image',
        ),
    ]
